name: pipeline

on: [push, pull_request]

jobs:
  dev:
    if: github.event.ref == 'refs/heads/dev'
    uses: balavellingiri/repo1/.github/workflows/template-dev.yaml@main
    with:
      var1: "hello-dev"
      var2: "world-dev"

  qa:
    if: github.event.ref == 'refs/heads/qa'
    uses: balavellingiri/repo1/.github/workflows/template-qa.yaml@main
    with:
      var1: "hello-qa"
      var2: "world-qa"

  uat:
    if: github.event.ref == 'refs/heads/main'
    uses: balavellingiri/repo1/.github/workflows/template-qa.yaml@main
    with:
      var1: "hello-uat"
      var2: "world-uat"

  prod:
    if: github.ref_type == 'tag'
    uses: balavellingiri/repo1/.github/workflows/template-qa.yaml@main
    with:
      var1: "hello-prod"
      var2: "world-prod"
